# https://taskfile.dev

version: '3'

includes:
  programs_hello_world:
    taskfile: ./libs/programs/hello-world
  anchor:
    taskfile: ./libs/anchor
  anchor_programs_basic_1:
    taskfile: ./libs/anchor/programs/basic-1
    dir: ./libs/anchor/programs/basic-1
